baseurl = "https://example.org/"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "Instamiam"
theme = "instamiam"
summaryLength = 10
removePathAccents=true

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "Dernières recettes"
    URL = "dernieres-recettes"
    weight = 2

    [[menu.nav]]
    name = "Catégories"
    URL = "categories"
    weight = 3

    [[menu.nav]]
    name = "Recettes les mieux notées"
    URL = "recettes-mieux-notees"
    weight = 4

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
logo = "images/logo.png"
# Meta data
description = "Recettes simples, familiales et gourmandes"
author = "carobee"
# Google Analitycs
googleAnalitycsID = "UA-6335497-8 "
custom_css = ["css/custom.css"]



    # footer
    [params.footer]
        copyright = "Carobee"
        copyrightURL = "http://www.carobee.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "https://www.facebook.com/instamiam"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "https://twitter.com/Instamiam"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "https://www.youtube.com/channel/UChcSUQwuQF5BA84sJ1VXnLA/videos"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"
        url = "http://pinterest.com/instamiam/"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-instagram"
        url = "http://instagram.com/instamiam_fr"
