baseurl = "https://instamiam.netlify.com"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "Instamiam"
theme = "instamiam"
summaryLength = 10
removePathAccents=true
enableRobotsTXT=true

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"
  video = "videos"

# Menu
[menu]
    [[menu.nav]]
    name = "Dernières recettes"
    URL = "dernieres-recettes"
    weight = 2

    [[menu.nav]]
    name = "Recherche"
    URL = "searchBox"
    weight = 3
    [[menu.nav]]
    name = "Catégories"
    URL = "categories"
    weight = 4

    [[menu.nav]]
    name = "Pratique les basiques"
    URL = "pratiques-les-basiques"
    weight = 5

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 6

# Site params
[params]
home= "Accueil"
logo = "images/logo.png"
# Meta data
description = "Recettes simples, familiales et gourmandes"
author = "carobee"
# Google Analitycs
googleAnalitycsID = "UA-6335497-8 "
custom_css = ["css/custom.css"]
logoAlgolia= "images/logo-algolia-white-full.png"

  # footer
  [params.footer]
      copyright = "Carobee"
      copyrightURL = "http://www.carobee.com"

      # social Icons
      [[params.footer.socialIcon]]
      icon = "tf-ion-social-facebook"
      url = "https://www.facebook.com/instamiam"

      [[params.footer.socialIcon]]
      icon = "tf-ion-social-twitter"
      url = "https://twitter.com/Instamiam"

      [[params.footer.socialIcon]]
      icon = "tf-ion-social-youtube"
      url = "https://www.youtube.com/channel/UChcSUQwuQF5BA84sJ1VXnLA/videos"

      [[params.footer.socialIcon]]
      icon = "tf-ion-social-pinterest-outline"
      url = "http://pinterest.com/instamiam/"

      # social Icons
      [[params.footer.socialIcon]]
      icon = "tf-ion-social-instagram"
      url = "http://instagram.com/instamiam_fr"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags", "ingredients"]

[outputs]
home = ["HTML", "RSS", "Algolia"]