baseurl = "https://instamiam.netlify.com"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "Instamiam"
theme = "dream"
summaryLength = 10
removePathAccents=true
enableRobotsTXT=true
copyright = "Copyright © 2020. All Rights Reserved"
rssLimit = 25

[author]
    name = "Caro"

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"
  video = "videos"

# Menu
[menu]
    [[menu.nav]]
    name = "Dernières recettes"
    URL = "dernieres-recettes"
    weight = 2

    [[menu.nav]]
    name = "Recherche"
    URL = "searchBox"
    weight = 3
    [[menu.nav]]
    name = "Catégories"
    URL = "categories"
    weight = 4

    [[menu.nav]]
    name = "Pratique les basiques"
    URL = "pratiques-les-basiques"
    weight = 5

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 6

# Site params
[params]
home= "Accueil"
logo = "images/logo.png"
# Meta data
description = "Recettes simples, familiales et gourmandes"
author = "Instamiam"
# Google Analitycs
googleAnalitycsID = "UA-6335497-8 "
custom_css = ["css/custom.css"]
# logoAlgolia= "images/logo-algolia-white-full.png"

# specifiques theme dream
background = "#F8F8F8"
backgroundImage = "/images/backgrounds/bears-garlic-lighter-60.jpg"
linkColor = "#fa749e"
avatar = "/images/logo.png"
motto = "Recettes simples, familiales et gourmandes"
categoriesLimitInHeader = 9
# headerBottomText = ""
rss = true
#utterancesRepo = "g1eny0ung/g1eny0ung.github.io"
email = "instamiam@gmail.com"
twitter = "Instamiam"
facebook = "instamiam"
instagram = "instamiam_fr"
pinterest = "instamiam"

siteStartYear = 2013

favicon = "/images/favicon.ico"

#highlightjs = true
# highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
#highlightjsExtraLanguages = ["ocaml"]
highlightjsTheme = "gruvbox-light"
#highlightjsThemeDark = "gruvbox-dark"

# search
enableSearch = true

# options
showSummaryCoverInPost = true

# dark mode
darkLinkColor = "darkseagreen"
darkNav = true
dark404 = true

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags", "ingredients"]

[outputs]
home = ["HTML", "RSS", "Algolia", "JSON"]