baseurl = "https://instamiam.netlify.com"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "Instamiam"
theme = "dream"
summaryLength = 10
removePathAccents=true
enableRobotsTXT=true
copyright = "Copyright © 2020. All Rights Reserved"
rssLimit = 25

[author]
    name = "Caro"

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"
  video = "videos"

# Site params
[params]
home= "Accueil"
logo = "images/logo.png"
# Meta data
description = "Recettes simples, familiales et gourmandes"
author = "Instamiam"
# Google Analitycs
googleAnalitycsID = "UA-6335497-8 "
custom_css = ["css/custom.css"]
# logoAlgolia= "images/logo-algolia-white-full.png"

# specifiques theme dream
background = "#F8F8F8"
backgroundImage = "/images/backgrounds/bears-garlic-lighter-60.jpg"
linkColor = "#fa749e"
avatar = "/images/logo.png"
motto = "Recettes simples, familiales et gourmandes"
categoriesLimitInHeader = 9
# headerBottomText = ""
rss = false
#utterancesRepo = "g1eny0ung/g1eny0ung.github.io"
email = "instamiam@gmail.com"
twitter = "Instamiam"
facebook = "instamiam"
instagram = "instamiam_fr"
pinterest = "instamiam"
youtube = "UChcSUQwuQF5BA84sJ1VXnLA"

siteStartYear = 2013

favicon = "/images/favicon.ico"

# search
enableSearch = true

# options
showSummaryCoverInPost = true
hasTwitterEmbed = true

# dark mode
darkLinkColor = "darkseagreen"
darkNav = true
dark404 = true

[outputs]
home = ["HTML", "RSS", "JSON"]