---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/category/yaourts
  label: Yaourts
  create: all
  match: "**/*"
- type: directory
  path: content/category/pratique-les-basiques
  label: Pratiques les basiques
  create: all
  match: "**/*"
- type: directory
  path: content/category/plats
  label: Plats
  create: all
  match: "**/*"
- type: directory
  path: content/category/miams-sucres
  label: Miams sucrés
  create: all
  match: "**/*"
- type: directory
  path: content/category/legumes
  label: Légumes
  create: all
  match: "**/*"
- type: directory
  path: content/category/confitures
  label: Confitures
  create: documents
  match: "**/*"
- type: directory
  path: content/category/apero
  label: Apero
  create: documents
  match: "**/*"
- type: document
  path: themes/instamiam/layouts/partials/dernieres-recettes.html
  label: Bloc dernieres recettes
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.62.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.62.2
